image: node:lts

stages:
  - setup
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

setup:
  stage: setup
  needs: []
  script:
    - npm install

test:version:
  stage: test
  needs: []
  script: make test
    