* Extension: Enforce Safe Search / Adult Content Filter
Sets the built-in adult content filter (most often: safe search) on Google,
YouTube, Bing, Yahoo, DuckDuckGo, Ixquick, Startpage, Dogpile, Yandex,
Vimeo, Reddit, Ecosia, Dailymotion, and Qwant.

[[https://addons.mozilla.org/de/firefox/addon/sas/][https://img.shields.io/amo/v/sas.svg]]
[[https://chrome.google.com/webstore/detail/jsguardian/fiopkogmohpinncfhneadmpkcikmgkgc][https://img.shields.io/chrome-web-store/v/fiopkogmohpinncfhneadmpkcikmgkgc.svg]]
* Versions
** 4.3.4
*** Firefox failed on Quant
    due to CORS implementation
** 4.3.0
*** Chrome complained about uri.includes
** 4.2.3
*** Broke Google Drive
** 4.2.2
*** Was exploitable
    credits to @sfrauenfelder
** 4.2.1
*** Broke everything
** 4.2.0
*** Might have added URL search parameter twice
** 4.1.2
*** Broke Google docs
** 4.1.1
*** Failed on first search on quant.com
** 4.1.0
*** Lacked Qwant.com
    Currently, this uses strict mode. If moderate mode works for you, you can file an issue to change this.
** 4.0.1
*** Failed to correctly set the option from the UI.
** 4.0.0
*** Lacked
    Youtube-configuration. Youtube offers at least three safe search settings:
    - no adult content
    - moderate safe search
    - strict safe search
    This extension previously only selected moderate safe search.
** 3.6.1
*** Failed
    for google maps shown via another url than maps.google.com
** 3.6.0
*** Lacked
    slightly cleaner code (=indexOf=)
** 3.5.1
*** Failed
    generally due to using wrong method
** 3.5.0
*** Lacked
    dailymotion.com support
** 3.4.2
*** Failed
    to search on google play and to show google maps
** 3.4.1
*** Offended
    Google's Chrome Web Store reviewers due to too many supported sites (too many keywords in description)
** 3.4.0
*** Lacked
    basic ecosia.org support
** 3.3.0
*** Lacked
    application-id for firefox (required for MS global install)
*** Had
    mismatched name on FF and Chrome
** 3.2.0
*** Lacked
    basic reddit support
** 3.1.0
*** Lacked
    extension short name and image attribution
** 3.0.0
*** Added
    vimeo
** 2.3.0
*** Changed
    did not work on Google Chrome's/Chromium's omnibox search
** 2.2.0
*** Added
    yandex.com
** 2.1.0
*** Changed
    code file lacked license mention
** 2.0.0
*** Changed
    Version bump: a copy of my version 0.1.0 at mozilla has version 1.0.
** 0.2.1
*** Added
    dogpile.com
** 0.2.0
*** Added
    startpage.com, ixquick.com
** 0.1.0
*** Added
    youtube
** 0.0.1
   1st: google, bing, yahoo, duckduckgo
* Uses Icons
  - https://www.iconfinder.com/icons/928435/explore_find_look_search_view_zoom_icon#size=128
  - https://www.iconfinder.com/icons/532631/insurance_protection_safe_safety_secure_security_shield_icon#size=128
